-- Create founding_members table for Paystack integration
CREATE TABLE IF NOT EXISTS founding_members (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  paystack_reference text,
  amount integer,
  currency text,
  status text DEFAULT 'active',
  founding_member_number integer GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  created_at timestamptz DEFAULT now()
);

-- Index for fast lookups by email and reference
CREATE INDEX IF NOT EXISTS founding_members_email_idx ON founding_members (email);
CREATE INDEX IF NOT EXISTS founding_members_paystack_reference_idx ON founding_members (paystack_reference);
