import { NextRequest, NextResponse } from 'next/server'
import { createHmac } from 'crypto'
import { supabaseAdmin } from '@/lib/database'
import { TEST_PAYMENT_THRESHOLD_KOBO } from '@/lib/paystack-constants'

const PAYSTACK_SECRET_KEY = process.env.PAYSTACK_SECRET_KEY || ''

function verifySignature(body: string, signature: string): boolean {
  if (!PAYSTACK_SECRET_KEY) return false
  const expected = createHmac('sha512', PAYSTACK_SECRET_KEY)
    .update(body)
    .digest('hex')
  return expected === signature
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.text()
    const signature = request.headers.get('x-paystack-signature') || ''

    if (!verifySignature(body, signature)) {
      console.error('Paystack webhook: invalid signature')
      return new NextResponse('Invalid signature', { status: 400 })
    }

    const event = JSON.parse(body) as {
      event: string
      data: {
        status: string
        reference: string
        amount: number
        currency: string
        customer: { email: string }
        metadata: { name?: string; [key: string]: unknown }
      }
    }

    if (event.event !== 'charge.success' || event.data.status !== 'success') {
      return new NextResponse('OK', { status: 200 })
    }

    const txn = event.data
    const email = txn.customer.email
    const name = (txn.metadata?.name as string) || ''
    const amount = txn.amount
    const currency = txn.currency
    const reference = txn.reference
    const is_test = amount <= TEST_PAYMENT_THRESHOLD_KOBO

    if (!supabaseAdmin) {
      console.error('Paystack webhook: supabaseAdmin is null')
      // Return 200 to prevent Paystack from retrying — Supabase is a backup
      return new NextResponse('OK', { status: 200 })
    }

    // Fire-and-forget Supabase upsert (backup in case verify endpoint was missed).
    // founding_member_number is GENERATED BY DEFAULT AS IDENTITY — DB assigns on insert,
    // preserved on conflict update.
    Promise.resolve().then(async () => {
      try {
        const { error } = await supabaseAdmin!
          .from('founding_members')
          .upsert(
            [{
              name,
              email,
              paystack_reference: reference,
              amount,
              currency,
              status: 'active',
              is_test,
            }],
            { onConflict: 'email' }
          )

        if (error) {
          console.error('Paystack webhook: founding_members upsert error', error)
        }

        await supabaseAdmin!
          .from('waitlist')
          .update({ status: 'converted' })
          .eq('email', email)
          .eq('status', 'pending')
      } catch (err) {
        console.error('Paystack webhook: async upsert error', err)
      }
    })

    return new NextResponse('OK', { status: 200 })
  } catch (error) {
    console.error('Paystack webhook unexpected error:', error)
    // Return 200 to prevent retries for parse errors
    return new NextResponse('OK', { status: 200 })
  }
}
